before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/gorillang/
  binary: gorillang
archives:
- replacements:
    darwin: Darwin
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - github:
      owner: momotaro98
      name: homebrew-gorillang
    folder: Formula
    homepage: https://github.com/momotaro98/gorillang
    description: gorillang
    test: |
      system "#{bin}/goreleaser -v"
